## Python Standard Library
The built in library for Python is one of its strengths, and ships with a number of built in types that are used constantly throughout any type of project. Alongside these are the number of functions as well that are built specifically to work within a Python environment. 

In [6]:
object_to_apply_function_on = [[1,2,2,1], [3,4], [5,6]]

# Map is one of Python's built-in functions
print(list(map(len, object_to_apply_function_on)))

[4, 2, 2]


In [7]:
print(list(map(lambda x: sum(x)/len(x), object_to_apply_function_on)))

[1.5, 3.5, 5.5]


Map takes a function that you are to apply to every element in a given object. The second example here showing how we can use a defined `lambda` function within `map` as well. 

In [12]:
print(range(0,10))
[*range(0,10)]

range(0, 10)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

You can see above that we used the unpacking syntax for `range` to unpack the `range` object into a list; we specify a list by the square brackets. 

## NumPy Arrays
They are a memory efficient alternative to the python `list`. They are homogenous, meaning that they must contain all elements of the same data type. It is this homogenous nature that allows for the removal of the type checking that is present in Python's base `list`. 

In [13]:
import numpy as np

In [14]:
list_a = [1,2,3,4,5,6]
array_a = np.array(list_a)
print(list_a)
print(array_a)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [15]:
# Broadcasting with numpy arrays 
array_a * 4

array([ 4,  8, 12, 16, 20, 24])

In [16]:
list_a * 4

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

Here we can see that `np.array` objects vectorise the process, whereas the `lists` multiplies the list and appends them together. 

In [17]:
array_a ** 3

array([  1,   8,  27,  64, 125, 216])

In [18]:
list_a ** 3

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [19]:
[x ** 3 for x in list_a]

[1, 8, 27, 64, 125, 216]

Here are 2 different methods for cubing the entire list/array of values. `np.array` doesn't involve looping through the list in order to calculate the cubes of every element. 